# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translate_manager', '0002_auto_20171202_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doc', models.FileField(blank=True, null=True, upload_to='translate_manager.DocFile/bytes/filename/mimetype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='translate_manager.Project')),
            ],
        ),
        migrations.CreateModel(
            name='DocFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='translate_manager.Project'),
        ),
    ]
